services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 'MyPassword!'
      MYSQL_DATABASE: store_api
      MYSQL_USER: raivydas
      MYSQL_PASSWORD: 'MyPassword!'
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: